// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewtonGamingStation.Infrastructure.Persistence;

#nullable disable

namespace NewtonGamingStation.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        BuildSharedModel(modelBuilder);
#pragma warning restore 612, 618
    }

    /// <summary>
    /// Shared model definition reused by the migration's target model so the snapshot
    /// stays in lock-step with the initial migration.
    /// </summary>
    internal static void BuildSharedModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("NewtonGamingStation.Domain.Entities.Publisher", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<string>("Country").HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("datetimeoffset");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<DateTimeOffset?>("UpdatedAtUtc").HasColumnType("datetimeoffset");
            b.HasKey("Id");
            b.HasIndex("Name").IsUnique();
            b.ToTable("Publishers");
        });

        modelBuilder.Entity("NewtonGamingStation.Domain.Entities.Role", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("datetimeoffset");
            b.Property<string>("Description").HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<DateTimeOffset?>("UpdatedAtUtc").HasColumnType("datetimeoffset");
            b.HasKey("Id");
            b.HasIndex("Name").IsUnique();
            b.ToTable("Roles");
        });

        modelBuilder.Entity("NewtonGamingStation.Domain.Entities.User", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("datetimeoffset");
            b.Property<string>("DisplayName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
            b.Property<DateTimeOffset?>("UpdatedAtUtc").HasColumnType("datetimeoffset");
            b.Property<string>("UserName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.HasKey("Id");
            b.HasIndex("Email").IsUnique();
            b.HasIndex("UserName").IsUnique();
            b.ToTable("Users");
        });

        modelBuilder.Entity("NewtonGamingStation.Domain.Entities.Game", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("datetimeoffset");
            b.Property<string>("Description").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
            b.Property<int>("Genre").HasColumnType("int");
            b.Property<string>("Platform").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<decimal>("Price").HasColumnType("decimal(10,2)");
            b.Property<int>("PublisherId").HasColumnType("int");
            b.Property<DateOnly>("ReleaseDate").HasColumnType("date");
            b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<DateTimeOffset?>("UpdatedAtUtc").HasColumnType("datetimeoffset");
            b.HasKey("Id");
            b.HasIndex("PublisherId");
            b.HasIndex("Title");
            b.ToTable("Games");
        });

        modelBuilder.Entity("NewtonGamingStation.Domain.Entities.UserRole", b =>
        {
            b.Property<int>("UserId").HasColumnType("int");
            b.Property<int>("RoleId").HasColumnType("int");
            b.Property<DateTimeOffset>("AssignedAtUtc").HasColumnType("datetimeoffset");
            b.HasKey("UserId", "RoleId");
            b.HasIndex("RoleId");
            b.ToTable("UserRoles");
        });

        modelBuilder.Entity("NewtonGamingStation.Domain.Entities.Game", b =>
        {
            b.HasOne("NewtonGamingStation.Domain.Entities.Publisher", "Publisher")
                .WithMany("Games")
                .HasForeignKey("PublisherId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
            b.Navigation("Publisher");
        });

        modelBuilder.Entity("NewtonGamingStation.Domain.Entities.UserRole", b =>
        {
            b.HasOne("NewtonGamingStation.Domain.Entities.Role", "Role")
                .WithMany("UserRoles")
                .HasForeignKey("RoleId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.HasOne("NewtonGamingStation.Domain.Entities.User", "User")
                .WithMany("UserRoles")
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Role");
            b.Navigation("User");
        });

        modelBuilder.Entity("NewtonGamingStation.Domain.Entities.Publisher", b =>
        {
            b.Navigation("Games");
        });

        modelBuilder.Entity("NewtonGamingStation.Domain.Entities.Role", b =>
        {
            b.Navigation("UserRoles");
        });

        modelBuilder.Entity("NewtonGamingStation.Domain.Entities.User", b =>
        {
            b.Navigation("UserRoles");
        });
    }
}
